### ISSUE TITLE
Update bucket variable query for new map function

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb-templates#4]
the template variable query for bucket needs to be updated. It should be changed to something like this: 

```
buckets()
  |> map(fn: (r) => ({ _value: r.name }), mergeKey: true)
```

**Comment by ebb-tide** [comment]
@nathanielc at some point we had spoken about adding the flux queries that we use in template dashboards/tasks to the tests in flux, so that we could get ahead of breaking changes to the flux library, have we done that?

**Comment by nathanielc** [comment]
@ebb-tide yes, several UI queries are now part of the Flux test suite, and new queries you add can also be added.

Using the `mergeKey` parameter is deprecated and should not be used, the new query should be this instead since the map is only being used to rename the column.

```
buckets()
  |> rename(columns: { name:"_value"})
```
