### ISSUE TITLE
Update queries using Map in templates

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb-templates#8]
We need to update the queries using the map function in all templates.

- [ ] https://github.com/influxdata/influxdb-templates/blob/d74fffdcc1e78444876603c8fe8082705d83cea7/templates/gettingStarted.json#L685
- [ ] https://github.com/influxdata/influxdb-templates/blob/d74fffdcc1e78444876603c8fe8082705d83cea7/templates/redis.json#L474
- [ ] https://github.com/influxdata/influxdb-templates/blob/d74fffdcc1e78444876603c8fe8082705d83cea7/templates/redis.json#L840
- [ ] https://github.com/influxdata/influxdb-templates/blob/d74fffdcc1e78444876603c8fe8082705d83cea7/templates/nginx.json#L435
- [ ] https://github.com/influxdata/influxdb-templates/blob/d74fffdcc1e78444876603c8fe8082705d83cea7/templates/nginx.json#L554
- [ ] https://github.com/influxdata/influxdb-templates/blob/d74fffdcc1e78444876603c8fe8082705d83cea7/templates/system.json#L342
- [ ] https://github.com/influxdata/influxdb-templates/blob/d74fffdcc1e78444876603c8fe8082705d83cea7/templates/system.json#L477
- [ ] https://github.com/influxdata/influxdb-templates/blob/d74fffdcc1e78444876603c8fe8082705d83cea7/templates/docker.json#L468
- [ ] https://github.com/influxdata/influxdb-templates/blob/d74fffdcc1e78444876603c8fe8082705d83cea7/templates/docker.json#L516
- [ ] https://github.com/influxdata/influxdb-templates/blob/d74fffdcc1e78444876603c8fe8082705d83cea7/templates/localMetrics.json#L870
- [ ] https://github.com/influxdata/influxdb-templates/blob/d74fffdcc1e78444876603c8fe8082705d83cea7/templates/localMetrics.json#L1072
- [ ] https://github.com/influxdata/influxdb-templates/blob/d74fffdcc1e78444876603c8fe8082705d83cea7/templates/kubernetes.json#L1004

**Comment by ebb-tide** [comment]
can we also bump the version numbers on those templates please? Just in case we decide to update dashboards with them one day..

**Comment by russorat** [comment]
yes. any change to a template should increment the version number for that template.
